# _Домашняя работа **1**_

## **Примеры использования NumPy**

### Импорт NumPy в общепринятом виде

In [22]:
import numpy as np

### Создание массивов в NumPy

Простое создание массива из классического списка Python

In [3]:
marks = np.array([4,5,5,3,2,5,4,4,3,5])
marks

array([4, 5, 5, 3, 2, 5, 4, 4, 3, 5])

Создание многомерного массива **n** x **m**, заполненного _нулями_ 

In [4]:
n,m = 3,5
weights = np.zeros((n,m))
weights

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Такое же создание многомерного массива **n**x**m**, заполненного _единицами_

In [5]:
n,m = 2,3
weights = np.ones((n,m))
weights

array([[1., 1., 1.],
       [1., 1., 1.]])

Создание одномерного массива с указанием последовательности чисел внутри (диапазона)

In [6]:
pages_for_load = np.arange(3,11)
pages_for_load

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Демонстрация примеров атрибутов для массива

Создаем для примера массив нулевых чисел 4 на 5

In [7]:
weights = np.zeros((4,5))

С помощью атрибута **shape** можно вывести кортеж размеров массива по каждой оси

In [8]:
weights.shape

(4, 5)

С помощью атрибута **ndim** можно вывести количество осей в массиве (одномерный - 1, двумерный - 2, ...)

In [9]:
weights.ndim

2

Атрибут **dtype** поможет узнать какой тип данных хранит массив

In [10]:
weights.dtype

dtype('float64')

### Индексирование и срезы

Создаем двумерный массив чисел для примеров

In [11]:
nums = np.arange(1,13).reshape(4,3) # используем функцию reshape для преобразования массива из одномерного в многомерный
nums

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

С помощью индексирования мы можем получить отдельные элементы массива

In [12]:
nums[1,2]

np.int64(6)

Также с помощью индексов можно делать срезы конкретных нужных частей массива

In [13]:
print(nums[1:3]) # 2 и 3 строки массива
print("-"*10)
print(nums[:,1]) # 2 столбец массива
print("-"*10)
print(nums[1:3,1:3]) # выбор среза 2х2

[[4 5 6]
 [7 8 9]]
----------
[ 2  5  8 11]
----------
[[5 6]
 [8 9]]


### Примеры векторных операций и базовых статистик

Массивы NumPy поддерживают очень удобные поэлементные операции, ниже приведу несколько примеров

Создание массива со статистикой роста людей, и прибавление к каждому значению 5

In [14]:
people_heights = np.array([168,192,185,157,178,169,173])

people_heights+5

array([173, 197, 190, 162, 183, 174, 178])

Можно взять корень из каждого значения

In [15]:
people_heights**(1/2)

array([12.9614814 , 13.85640646, 13.60147051, 12.52996409, 13.34166406,
       13.        , 13.15294644])

Также перевод каждого значения из сантиметров в метры

In [16]:
people_heights/100

array([1.68, 1.92, 1.85, 1.57, 1.78, 1.69, 1.73])

Создание статистики количества людей с ростом больше 175

In [17]:
people_heights>175

array([False,  True,  True, False,  True, False, False])

Для дальнейшей работы нам часто приходится использовать статистику по используемым массивам

Для нахождения среднего значения будем использовать функцию mean

In [18]:
people_heights.mean()

np.float64(174.57142857142858)

Классический поиск максимального max() и минимального min()

In [19]:
print(people_heights.max())
print(people_heights.min())

192
157


Для примера хотелось бы еще привести использование функции стандартного отклонения std() (можно использовать как для всего массива так и по осям)

In [21]:
people_heights.std()

np.float64(10.755160128410692)